add landing w/o lang-function
minimal-dev/xtrx pull request #1
Opened 2020-11-28 13:20 UTC by animetalist

2020-11-28 13:20 UTC, minimal-dev commented
Task linked: [CU-acx0gt Homepage](https://app.clickup.com/t/acx0gt)

2020-11-28 17:05 UTC, salexpro requested changes
- убрать шрифты
- комменты со слака

2020-11-28 17:05 UTC, salexpro commented on src/scss/sections/_benefits.scss
> +        display: block;
это заменяется `breakpoint(medium){}`

2020-11-28 17:05 UTC, salexpro commented on src/scss/sections/_benefits.scss
> +    }
тут луче будет сделать, ставишь по дефолту то что на nth-child(2), а остальное на first и last child, так если добавится допустим 4й элемент визуально не сильно сломается

2020-11-29 15:09 UTC, salexpro approved these changes

2020-12-09 04:45 UTC, salexpro approved these changes

2020-12-09 04:45 UTC, merged